// Copyright (c) 2025 Adrián Quiroga Linares Lectura y referencia permitidas; reutilización y plagio prohibidos

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.TipoUsuario;
import aplicacion.Usuario;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author alumnogreibd
 */
public class Vusuarios extends javax.swing.JDialog {
    FachadaAplicacion fa;
    Boolean nuevoPulsado;
    
    /**
     * Creates new form Vusuarios
     */
    public Vusuarios(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        nuevoPulsado=false;
        idTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoBuscarID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoBuscarNombre = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        claveTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SalirButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        nuevoButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Usuarios");

        jLabel1.setText("ID:");

        textoBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBuscarIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        textoBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBuscarNombreActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablaUsuarios.setModel(new ModeloTablaUsuarios());
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jLabel3.setText("ID:");

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        claveTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo:");

        tipoComboBox.setModel(new DefaultComboBoxModel(TipoUsuario.values()));
        tipoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Email:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Dirección:");

        jLabel8.setText("Clave:");

        SalirButton.setText("Salir");
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        borrarButton.setText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        nuevoButton.setText("Nuevo");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textoBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nuevoButton)
                                .addGap(53, 53, 53)
                                .addComponent(guardarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreTextField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(borrarButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(claveTextField)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(direccionTextField)
                                    .addComponent(tipoComboBox, 0, 118, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SalirButton)))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textoBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(claveTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirButton)
                    .addComponent(borrarButton)
                    .addComponent(nuevoButton)
                    .addComponent(guardarButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBuscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoBuscarIDActionPerformed

    private void textoBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBuscarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoBuscarNombreActionPerformed

    private void claveTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveTextFieldActionPerformed

    private void tipoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoComboBoxActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        borrarUsuario();
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        buscarUsuarios();
    }//GEN-LAST:event_BuscarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        ModeloTablaUsuarios m;
        m=(ModeloTablaUsuarios)tablaUsuarios.getModel();
        
        Usuario selectedtUser = m.obtenerUsuario(tablaUsuarios.getSelectedRow());
        
        idTextField.setText(selectedtUser.getIdUsuario());
        claveTextField.setText(selectedtUser.getClave());
        nombreTextField.setText(selectedtUser.getNombre());
        emailTextField.setText(selectedtUser.getEmail());
        direccionTextField.setText(selectedtUser.getDireccion());
        tipoComboBox.setSelectedItem(selectedtUser.getTipoUsuario());
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        if(nuevoPulsado){
            guardarUsuario();
            idTextField.setEditable(false);
        }
        else{
            editarUsuario();
        }
        
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed
        idTextField.setEditable(true);
        nuevoUsuario();
        nuevoPulsado=true;
        
    }//GEN-LAST:event_nuevoButtonActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = tablaUsuarios.getSelectedRow();
        if (fila != -1) { 
            ModeloTablaUsuarios m = (ModeloTablaUsuarios) tablaUsuarios.getModel();
            Usuario selectedUser = m.obtenerUsuario(fila);

            // Llenar los campos con la información del usuario seleccionado
            idTextField.setText(selectedUser.getIdUsuario());
            claveTextField.setText(selectedUser.getClave());
            nombreTextField.setText(selectedUser.getNombre());
            emailTextField.setText(selectedUser.getEmail());
            direccionTextField.setText(selectedUser.getDireccion());
            tipoComboBox.setSelectedItem(selectedUser.getTipoUsuario());
        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed

    }//GEN-LAST:event_idTextFieldActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton SalirButton;
    private javax.swing.JButton borrarButton;
    private javax.swing.JTextField claveTextField;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton guardarButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField textoBuscarID;
    private javax.swing.JTextField textoBuscarNombre;
    private javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables

    
    
    private void borrarUsuario() {
        verificarCamposBorrar();
        ModeloTablaUsuarios m;
        m = (ModeloTablaUsuarios) tablaUsuarios.getModel();

        if (!idTextField.getText().isEmpty()) {
            fa.eliminarUsuario(idTextField.getText());
            
        }
        buscarUsuarios();
        nuevoUsuario();
    }


    private void nuevoUsuario() {
        idTextField.setText("");
        claveTextField.setText("");
        nombreTextField.setText("");
        emailTextField.setText("");
        direccionTextField.setText("");
        tipoComboBox.setSelectedIndex(0); 
    }

    private void guardarUsuario() {
        if(verificarCamposGuardar()){
            ModeloTablaUsuarios m;
            m = (ModeloTablaUsuarios) tablaUsuarios.getModel();
            m.setFilas(fa.obtenerUsuarios(idTextField.getText(), nombreTextField.getText()));

            Usuario u = new Usuario(idTextField.getText(), claveTextField.getText(), nombreTextField.getText(),
                    emailTextField.getText(), direccionTextField.getText(), TipoUsuario.valueOf(tipoComboBox.getSelectedItem().toString()));

            fa.guardarUsuario(u);
        }
        else{
            fa.muestraExcepcion("Debes cubrir todos los campos, para poder crear un nuevo usuario");
        }
        buscarUsuarios();
        nuevoUsuario();
    }
    
    private void editarUsuario() {
        if(verificarCamposGuardar()){
            ModeloTablaUsuarios m;
            m = (ModeloTablaUsuarios) tablaUsuarios.getModel();
            m.setFilas(fa.obtenerUsuarios(idTextField.getText(), nombreTextField.getText()));
            
            fa.editarUsuario(idTextField.getText(), claveTextField.getText(), nombreTextField.getText(),
                    emailTextField.getText(), direccionTextField.getText(), TipoUsuario.valueOf(tipoComboBox.getSelectedItem().toString()));
        }
        else{
            fa.muestraExcepcion("Debes cubrir todos los campos, para poder crear un nuevo usuario");
        }
        buscarUsuarios();
        nuevoUsuario();
    }
    

    // Método para habilitar el botón de "Guardar" solo si todos los campos están completos
    private boolean verificarCamposGuardar() {
        return !idTextField.getText().isEmpty() && !claveTextField.getText().isEmpty() &&
                                   !nombreTextField.getText().isEmpty() && !emailTextField.getText().isEmpty() &&
                                   !direccionTextField.getText().isEmpty();

        
    }
    
    private void verificarCamposBorrar() {
        boolean habilitarGuardar = !idTextField.getText().isEmpty();

        borrarButton.setEnabled(habilitarGuardar);
    }

    private void buscarUsuarios() {
        ModeloTablaUsuarios m;
        m = (ModeloTablaUsuarios) tablaUsuarios.getModel();
        m.setFilas(fa.obtenerUsuarios(textoBuscarID.getText(), textoBuscarNombre.getText()));

        if (m.getRowCount() > 0) {
            
            tablaUsuarios.setRowSelectionInterval(0, 0);
            idTextField.setText(m.obtenerUsuario(tablaUsuarios.getSelectedRow()).getIdUsuario());
            claveTextField.setText(m.obtenerUsuario(tablaUsuarios.getSelectedRow()).getClave());
            nombreTextField.setText(m.obtenerUsuario(tablaUsuarios.getSelectedRow()).getNombre());
            emailTextField.setText(m.obtenerUsuario(tablaUsuarios.getSelectedRow()).getEmail());
            direccionTextField.setText(m.obtenerUsuario(tablaUsuarios.getSelectedRow()).getDireccion());
            tipoComboBox.setSelectedItem(m.obtenerUsuario(tablaUsuarios.getSelectedRow()).getTipoUsuario());

            
            guardarButton.setEnabled(true);
            borrarButton.setEnabled(true);
        } else {
            guardarButton.setEnabled(false);
            borrarButton.setEnabled(false);
        }
        nuevoPulsado=false;
    }

    

    
    
}
